director_uuid: 55c7e258-ea60-4342-a314-a704179d6760

name: kubernetes

releases:
- name: etcd
  version: latest
- name: kubernetes
  version: latest

networks:
- name: etcd
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.4.0/30
    reserved:
    - 10.244.4.1
    static:
    - 10.244.4.2
- name: kubernetes_master
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.5.0/30
    reserved:
    - 10.244.5.1
    static:
    - 10.244.5.2
- name: compilation
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.6.0/30
    reserved:
    - 10.244.6.1
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.4/30
    reserved:
    - 10.244.6.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.6.8/30
    reserved:
    - 10.244.6.9
    static: []
  type: manual

compilation:
  cloud_properties: {}
  network: compilation
  reuse_compilation_vms: true
  workers: 3

resource_pools:
- cloud_properties: {}
  name: etcd
  network: etcd
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- cloud_properties: {}
  name: kubernetes_master
  network: kubernetes_master
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
- instances: 1
  name: etcd
  networks:
  - name: etcd
    static_ips:
    - 10.244.4.2
  persistent_disk: 1024
  resource_pool: etcd
  templates:
  - name: etcd
    release: etcd
- instances: 1
  name: master
  networks:
  - name: kubernetes_master
    static_ips:
    - 10.244.5.2
  resource_pool: kubernetes_master
  templates:
  - name: flannel
    release: kubernetes
  - name: docker
    release: kubernetes

properties:
  etcd:
    machines:
    - 10.244.4.2
    peer_require_ssl: false
    require_ssl: false
  kubernetes:
    flannel:
      etcd:
        endpoints: ["http://10.244.4.2:4001"]
      pod_network: 10.244.7.0/24
